version: "3"

services:
  mysql_db:
    container_name: mysql_db
    image: mysql
    restart: unless-stopped
    volumes:
      - ./.mysql/data:/var/lib/postgresql/data
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABSE=sbeauty
